### ISSUE TITLE
Staking accounts not showing up in my solflare wallet (synced to ledger hardware)

### ISSUE THREAD

**Issue by Roycris** [solana-beach/issue-tracker#11]
**Describe the bug**
Deposited and staked my solana tokens on solflare few weeks ago but suddenly there's no staking accounts anymore when I login to solflare. Any idea?

**Comment by rpd089** [comment]
Hi @Roycris, thanks for reaching out. There have been some synchronization issues w.r.t. Stake Accounts and Solflare. However, the Solflare team was hard at work yesterday and the issue has been resolved from what I take from the Solflare Telegram channel: https://t.me/SolFlare_Wallet
