### ISSUE TITLE
Binance Node does not show its name, same for all validators without a "keybase id"

### ISSUE THREAD

**Issue by bji** [solana-beach/issue-tracker#12]
**Describe the bug**
Binance Node has vote account 47e2BfrzbWdDieFZA7fc9fX1f73WTtkok2fQxSb8GueY and validator id account tDw82DpNQwC4sUqRt5zCihm1N9ktta51ZyXbWewMsWp.  It has validator info showing its name as "Binance Node".  But solanabeach.io does not actually display its name in the list of validators, only its vote key.

Actually as I look more closely, it appears that any validator that does not have a keybase id does not show its name even if it has a name registered with validator info.  I will update the issue title.

**Comment by rpd089** [comment]
Hey @bji, thanks for reaching out to us. We pull the validator 'profile' info directly from keybase, so if a validator does not have a keybase id, we do not display the validators' name or profile picture. What do you mean

**Comment by rpd089** [comment]
Hey @bji, thanks for reaching out to us - we are looking into this. Appreciate you taking the time to report this!
