### ISSUE TITLE
Slot success rate showing "N/A"

### ISSUE THREAD

**Issue by JulesTan** [solana-beach/issue-tracker#13]
**Describe the bug**
Mainnet validator been voting >2 Epoch but does not have slot success rate calculated.

**To Reproduce**
1. Go to 'https://solanabeach.io/validator/8W67HRaD6knTKHxZWW7ZqK452r2qWMdjqW4SG62tijLt'
2. Under "Validator Details", see "Slot success rate" 

**Expected behavior**
"Slot success rate" shows "N/A"

**Desktop (please complete the following information):**
 - Browser [Brave, Chrome, Safari]
<img width="1097" alt="slot_success_rate_na" src="https://user-images.githubusercontent.com/935517/126800724-fcb7a27e-d3bd-4e28-bf71-56e95e84e4ec.png">

**Comment by rpd089** [comment]
Thanks for reporting this, @JulesTan - we'll look into it!

**Comment by rpd089** [comment]
Hey @JulesTan, so we display N/A in case the validator didn't have any leader slots up to this point in the current epoch - we'll adjust the tooltip accordingly.

**Comment by JulesTan** [comment]
Thanks. I will continue to monitor.
