### ISSUE TITLE
Include APY info for validators

### ISSUE THREAD

**Issue by bji** [solana-beach/issue-tracker#14]
**Is your feature request related to a problem? Please describe.**
Users cannot tell returns information in the solanabeach.io validator list.  All they can see is commission, and this is a misleading value that roughly correlates with returns (which is what people really care about) but is not a perfect correlation.  This lack of accurate information could be seen as a problem.

**Describe the solution you'd like**
The APY data for all validators is available:
https://stakeview.app/apy/prev3.json
https://stakeview.app/apy/prev10.json

The first link is the average APY of previous 3 epochs for every validator, the second link is average of the previous 10 epochs.  I recommend that your site downloads these values and uses them to look up and display an APY value for each validator (probably the prev3 data is best).  

You can read about this data at:

https://stakeview.app/data.html

**Describe alternatives you've considered**
You could do your own APY calculation but this is complex.  You have to find a delegated stake account for a previous set of epochs, look up its returns, and calculate APY based on that and the epoch durations, which also have to be looked up.  Much easier to just use the data already provided and described above.

**Additional context**
At least one user has requested this:

https://www.reddit.com/r/solana/comments/osq4v0/solanabeachio_your_review_matters_what_do_you/h6qoj1a/

It seems like the kind of thing a lot of users would like.

**Comment by bji** [comment]
Let me amend this: I recommend REPLACING the commission column with an APY column.  This is because we need to be discouraging users from looking at commission, commission wars are bad for everyone, and low commission does not necessarily translate to better returns.  Commission is just one factor in returns and having it called out separately is just not something that helps people make a better choice.  An APY column will tell people with much greater accuracy and fidelity what returns they can expect.  Please remove Commission and replace with APY.

**Comment by rpd089** [comment]
Awesome, thanks for psoting this @bji - we are working on it as this is dev. an awesome feature to have. W.r.t. the commission fee, you are right that commission wars are bad for the network, however I believe that as a block explorer, we should show this metric too.

**Comment by bji** [comment]
> Awesome, thanks for psoting this @bji - we are working on it as this is dev. an awesome feature to have. W.r.t. the commission fee, you are right that commission wars are bad for the network, however I believe that as a block explorer, we should show this metric too.

You could show the commission only in the validator details page like you show other details such as "slot success rate".

**Comment by bji** [comment]
Closing so I don't have to look at it in my list of Pull Requests anymore, given that Staking Facilities will never take action on this.
