### ISSUE TITLE
old gSAIL still displayed instead of new gSAIL

### ISSUE THREAD

**Issue by solanasail** [solana-beach/issue-tracker#16]
Hi SolanaBeach team,

We have migrated gSAIL to the new gSAIL.

Even if our PR on Solana-labs Token-list has been merged, the wrong name still display for the old gSAIL, and the new one is not display.

Here is our PR approved by Solana
https://github.com/solana-labs/token-list/pull/731

Regards,
SolanaSail Founder.

**Comment by rpd089** [comment]
It's update (logo needs to be changed, which will be done asap) - I'll close this task, thanks for reaching out to us and setting sail for solana ;)

**Comment by solanasail** [comment]
Thanks but on the new gSAIL mint is OK but not the logo, it's the 'OLD' one

**Comment by rpd089** [comment]
Yeah that's on me - I requested a change, should be up soon. Sorry for that!

**Comment by solanasail** [comment]
Thanks, sorry but still the old logo.
<img width="1118" alt="Capture d’écran 2021-09-03 à 22 34 42" src="https://user-images.githubusercontent.com/84818641/132062866-e4559bd2-c6fa-4557-a2dc-c0fa526332bc.png">

**Comment by solanasail** [comment]
Hi SolanaBeach team, @rpd089 

The old logo still displayed on the gSAIL SolanaSail Governance token V2 since 25 days now. May I ask you to update it ?

Regards,
