### ISSUE TITLE
Sticky header for validator list

### ISSUE THREAD

**Issue by mankinskin** [solana-beach/issue-tracker#17]
**Is your feature request related to a problem? Please describe.**
When scrolling through the validator list, it can become tedious to remember the column meaning or having to scroll back to the top, especially for infrequent users. Also, the sticky navigation bar makes confusions possible when navigation bar items align with list columns.

**Describe the solution you'd like**
Make the validator list header sticky so it doesn't scroll off-screen.

**Describe alternatives you've considered**
An alternative, if for example a sticky header takes too much vertical space, would be to add hover tooltips to list data.

**Comment by rpd089** [comment]
Hey @mankinskin, thanks for reaching out and requesting this feat, we appreciate it! Dully noted and on it - stay tight, we this feat is coming to a beach near you ;)
