### ISSUE TITLE
Rate Limited API Keyless

### ISSUE THREAD

**Issue by karadikid** [solana-beach/issue-tracker#22]
**Is your feature request related to a problem? Please describe.**
I would like to use your service in our open source websites without an API Key. This makes forking and upgradeability much easier. 

**Describe the solution you'd like**
A rate-limited keyless API would serve here.

Examples:
1. Different URI
2. Whitelist specific queries
3. Size limit
4. Depth limit
5. Rate limit

**Describe alternatives you've considered**
I have already applied for an API key short-term and will seek other avenues to get non-API key limited datasources.

**Additional context**
[Stakers.info](https://stakers.info) is one site I am trying to support.

**Comment by rpd089** [comment]
Hey @karadikid, thanks for reaching out to us - we'd love for open source projects to use the Sonalan Beach API. However, right now we can't get rid of the rate limits, as we would run into trouble ourselves then too. We'd appreciate it, if you could send any project looking for a key our way and share this with them: https://github.com/solana-beach/api
