### ISSUE TITLE
Weighted Skip Rate is very wrong

### ISSUE THREAD

**Issue by mvines** [solana-beach/issue-tracker#23]
https://solanabeach.io/validators currently reports a skip rate of:
![image](https://user-images.githubusercontent.com/1281082/133871799-cd881925-ec45-4961-9b17-c19d60cc17fd.png)

whereas actual skip rate, as correctly reported by `solana validators` output is 
```
Average Stake-Weighted Skip Rate: 3.65%
Average Unweighted Skip Rate:     5.94%
```

This is causing Solana FUD as people see number on Solana Beach and get confused

**Comment by rpd089** [comment]
Hey @mvines, thanks for reaching out and reporting this - we are looking into it!
