### ISSUE TITLE
cannot find my tokens anymore in my Solflare Wallet

### ISSUE THREAD

**Issue by Cjagroenewoud** [solana-beach/issue-tracker#26]
I cannot find my Codi tokens anymore in my Wallet, can someone help my?

**Comment by Nelson2176** [comment]
Hello to clarify I sent  1.01757 ETH BY MISTAKE TO MY SOLANA ADRESS IN TRUST WALLET ; 

2T8P7PM5FWU9dbQZEQkKrPofoRwccGyiHGgs3fuZD2Ba


Signature ; 4F7YJVh9FsAPG16ZN5D4mGYjybnQ7YbcZ22use9f1xH6M8BdC9DKdbTvk6UDPpd1kkMjF8NsGAQCz4dcgYeYAuut  

Block. 106856290 


Recent Blockhash.  7SHdZEcjfECAH7zw1in9mTXQu6N4gnkdwiPHazEW5hbw

TIME STAMP     Nov 14, 2021 at 10:02:31 Eastern Standard Time

Thanks for your help 
I’m very worry for my investment 
Nelson
