### ISSUE TITLE
How to withdraw funds from solanabeah.io

### ISSUE THREAD

**Issue by Obliviator1** [solana-beach/issue-tracker#27]
There is not a clear way to withdraw SOL from solanabeach.io and there should be so anyone including myself can withdraw their SOL when needed.

**Comment by ibaguign** [comment]
I staked some sol and I am not seeing it anymore on my phantom wallet and I can find a way to unstack them. Have I been scamed?

**Comment by rpd089** [comment]
Hey guys, please excuse the delayed reply. 

In case you staked your SOL via the 'stake' button on Solana Beach, you can simply get back to your staking operations via https://solflare.com/

Via the Solflare wallet, which you can access through the link above, you can e.g. switch validators, withdraw etc. You can learn how to do so with our guides:

Using Solflare w/ a hardware wallet: 
https://stakingfac.medium.com/how-to-stake-on-solana-with-solflare-a-ledger-nano-s-bdcc90d769c7
Using Solflare w/o a hardware wallet:
https://stakingfac.medium.com/how-to-stake-on-solana-with-solflare-a-keystore-file-9f7cd5fba169

In case you want to use Phantom wallet going forward, you'd need to import your the account you created via Solflare into Phantom first.
