### ISSUE TITLE
Missing transaction 

### ISSUE THREAD

**Issue by akaninyene-etuk** [solana-beach/issue-tracker#31]
Made a withdrawal of 0.1 sol , this morning which showed successfull but 4 hours after the withdrawal has not reflected in my binance account.

**Comment by Elija777** [comment]
hi i send renluna and wluna to sol binance adress . how can i retrieve my luna. have the signature and i can see the coins in my portfolio on step finance and solana beach. please help me to get it back. made a mistake

**Comment by GusVarela** [comment]
Hi! Im using legacy.solflare.com wallet to stake SOL. 
On 5th of Nov I undelegated that; the order is done, it said Success on SolanaBeach, but in my wallet still appears like staked, and i cannot do that again ( split or undelegate..) it said that is yet deactivate.
What can i do?? maybe is blocked?? how long it takes to receive my SOL? Please... Thank you!
