### ISSUE TITLE
Question: How do you calculate APY?

### ISSUE THREAD

**Issue by xdzurman** [solana-beach/issue-tracker#32]
Hello, you provide 'Nominal Staking APY'. For validation, how is this calculated and why can I trust it? According to documentation, it is calculated like this
![image](https://user-images.githubusercontent.com/22454337/142478909-e161a836-0561-402e-8289-4c1016917d4b.png)
Do you choose a different way?

**Comment by rpd089** [comment]
Hey @xdzurman, thanks for reaching out - we calculate this value as follows
<img width="570" alt="Bildschirmfoto 2021-12-06 um 09 36 10" src="https://user-images.githubusercontent.com/58171762/144813422-085b0afb-c8cf-4a25-9623-7c35e66a4f71.png">
:
