### ISSUE TITLE
fetchAccountTokens is timing out

### ISSUE THREAD

**Issue by c0dehunter** [solana-beach/issue-tracker#34]
The API endpoint https://app.swaggerhub.com/apis-docs/V2261/solanabeach-backend_api/0.0.1#/Account/fetchAccountTokens only works sometimes, but mostly it just times out.

![image](https://user-images.githubusercontent.com/1484658/146538411-80f4c59f-adc0-42da-a323-27212fe8a26f.png)

**Comment by esolanabeach** [comment]
Hi @c0dehunter, at the moment, it looks like the `/account/{pubkey}/tokens` endpoint should be up and working. I know a couple of weeks ago we were experiencing some outages and there were only a handful of the `/account` endpoints working at that time.

**Comment by c0dehunter** [comment]
I checked the logs and it seems to be working well now, yes. Thank you!
