### ISSUE TITLE
Solana Beach not showing SPL Token Details in every network.

### ISSUE THREAD

**Issue by Hariienesh1901** [solana-beach/issue-tracker#37]
**Describe the bug**
Solana Beach is redirecting me to a 404 page when I tried to see my SPL Token Details. I am in DevNet but it's also not working on Mainnet

**To Reproduce**
1. Go to 'https://solanabeach.io/address/Fx8JwEA9B7YxJrKpjoMt6Cxxnukqj4TQPTkniGcB4WsA?cluster=devnet'
2. Click on 'VIEW TOKEN'

**Expected behavior**
Show my Token Name, Token Symbol, Token Logo and other Token Details

**Screenshots**
![image](https://user-images.githubusercontent.com/76608849/151741392-64be7958-fd3a-4167-9560-2cbac7ed059d.png)
![image](https://user-images.githubusercontent.com/76608849/151741422-8bcc65a6-0cec-4654-86c6-381b620987a8.png)
![image](https://user-images.githubusercontent.com/76608849/151741442-4bbc0608-a23b-49a5-a0ea-a89be7874ea6.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
*Note: I didn't fill Desktop's Version because I don't know what it means. I didn't fill Smart Phone because I am not using it, It doesn't works on any network (Mainnet And DevNet)

**Comment by SimonKraus** [comment]
This was a temporary outage back then and is meanwhile fixed 🙏
