### ISSUE TITLE
Validator changed vote account showing deliquent

### ISSUE THREAD

**Issue by jpbogle** [solana-beach/issue-tracker#39]
### Discussed in https://github.com/solana-beach/issue-tracker/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **jpbogle** April 11, 2022</sup>
https://solanabeach.io/validators

Our validator (Cardinal) has been showing delinquent and also showing both vote accounts

We changed the vote account and it has been deliquent since but the dashboard shows that it is still voting
https://solana.thevalidators.io/d/e-8yEOXMwerfwe/solana-monitoring?orgId=2&refresh=30s&var-cluster=mainnet-beta&var-server=Cardinal

Can someone explain why this is showing up as deliquent?</div>

**Comment by SimonKraus** [comment]
Hi Jeremy, 

we did some investigation and it looks like the validator with the new vote key did not produce a block yet.
As soon as this happens it should show up as active again.

We will improve the handling in the future by taking votes for other blocks into account.

And if you want the remove the old vote account from the validator list you could reap the account by transferring off all SOL funds.

**Comment by jpbogle** [comment]
hey @SimonKraus thanks for the response!

That makes sense ya ideally votes for other blocks should be counted as non-deliquent? And thanks for tip about getting the old one to go away 👍 

I drained the balance for the old one and now all of a sudden the new one is also not showing as deliquent anymore! thanks

**Comment by SimonKraus** [comment]
Alrighty!! Awesome.

Appreciate the feedback!

My first guess was that data is mixed up cause both vote accounts had the same identity. 

Glad it's sorted so we can close this.
