### ISSUE TITLE
'Staked' SOL not being reported on Solana Beach - issue since 28 March 2023

### ISSUE THREAD

**Issue by ghvnct** [solana-beach/issue-tracker#45]
**Describe the bug**
Solana Beach is not picking up any 'Stakes" when a wallet has SOL staked in a validator 

**To Reproduce**
Login to the Solana Beach UI
1. Enter a Wallet Address (4QCEiKzXarQxzJTrX3x1i1QxR5176BPAXfUsLVne5mFD) with SOL staked in a validator
2. Click on 'Stakes'
3. Scroll down to view stakes .... list is empty

or 

Lookup wallet account on Solana Beach API
1. Run API endpoint

curl -X 'GET' \
  'https://api.solanabeach.io/v1/account/4QCEiKzXarQxzJTrX3x1i1QxR5176BPAXfUsLVne5mFD/stakes' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer XXXXXXXX'  \
| tee stakes.json

2. No data is returned.

**Expected behavior**
The given wallet address (4QCEiKzXarQxzJTrX3x1i1QxR5176BPAXfUsLVne5mFD) should have 10,950.18 SOL staked across 4 separate validators.

**Screenshots**
Verified with other Solana Block Explorers:
https://solscan.io/account/4QCEiKzXarQxzJTrX3x1i1QxR5176BPAXfUsLVne5mFD#stakeAccounts

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] All
 - Browser [e.g. chrome, safari] All

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] All
 - OS: [e.g. iOS8.1] All
 - Browser [e.g. stock browser, safari] All

**Additional context**

**Comment by ghvnct** [comment]
Is anyone reviewing these issue logs?

**Comment by SimonKraus** [comment]
Hey @ghvnct 👋

For sure we do.
I forwarded it to the devs within 30 minutes after creation. 
Sorry for not updating the status.

**Comment by SimonKraus** [comment]
It's not just an indexing issue but requires modification in the codebase, but @xlfpx is working on it 🙏

**Comment by ghvnct** [comment]
Thanks, it is now fixed

**Comment by xlfpx** [comment]
Closing this as the issue was resolved
