### ISSUE TITLE
help me my SOL token not back, this is proof of my transaction via phantom wallet

### ISSUE THREAD

**Issue by kdoubleoscar** [solana-beach/issue-tracker#46]
help me my SOL token not back, this is proof of my transaction via phantom wallet

https://solscan.io/tx/36Q8jukKKDVugSQsxnd4FuhGTZD6DgLjszsBHLsk2jctrA6tzFLzQy9s3QnfGhXNJuBTajsWE4KpqEyxTLTxzigH

Help Me 🙏

**Comment by SimonKraus** [comment]
The receiver address of the transaction is none that StakingFacilities or SolanaBeach controls so we sadly cannot help you with this.

SolanaBeach is just a blockchain explorer and nobody can revert the transaction for you.

If you know the receiver you sent the SOL tokens to you should get in touch with them and kindly ask to send it back to the sender.

If you have further question feel free to get in touch.
