### ISSUE TITLE
No staking rewards since June 8

### ISSUE THREAD

**Issue by nyg** [solana-beach/issue-tracker#47]
**Describe the bug**
Staking rewards are not being reported since epoch 458.

**To Reproduce**
* Rewards on Solana Beach: https://solanabeach.io/address/J1ZEdq7UcwfSsVqNyGuN3U8ewuWafpnQ9b3t1YMNqKr9/stake-rewards
  * Last epoch is 458
* Rewards on Solcan: https://solscan.io/account/J1ZEdq7UcwfSsVqNyGuN3U8ewuWafpnQ9b3t1YMNqKr9#rewards
  * Last epoch is 461

**Expected behavior**
Rewards for epoch 461 should be available in https://api.solanabeach.io/v1/account/J1ZEdq7UcwfSsVqNyGuN3U8ewuWafpnQ9b3t1YMNqKr9/stake-rewards

We would greatly appreciate if you could fix this :)

**Comment by SimonKraus** [comment]
Thanks for reporting, the indexer is having trouble 🙏

**Comment by nyg** [comment]
Hello, thanks for the quick answer. It seems the issue has been resolved, I can see rewards up to epoch 462. Thanks a lot!

**Comment by SimonKraus** [comment]
Thanks a lot for the feedback 🙏
