### ISSUE TITLE
Cannot read properties of null (reading 'historic')

### ISSUE THREAD

**Issue by MatrixYe** [solana-beach/issue-tracker#49]
When I try to open my validator page, I get the following error：
![image](https://github.com/user-attachments/assets/0c8b5479-9439-4da1-883c-19b0180ddb2c)

validator identity：GBfXyCU338aKXhQ2oHuvxcy7f6ufoJUPwivfnNSKAqyn
validator info account：6oGdJguqDcpXLinyp9GhJdJbMaXpSuPeYiVtgbFNfysH
vote account：CZQhsF5HbFbJbeGvTrZFwa8BkboqXAaHeoZVD7DecEQo

[In Solana Beach]( https://solanabeach.io/validator/CZQhsF5HbFbJbeGvTrZFwa8BkboqXAaHeoZVD7DecEQo)

**Comment by SimonKraus** [comment]
The Validator was activated in epoch 646, which ended on 25th of July.
You need to wait that activation epoch, now it's all sorted.
