### ISSUE TITLE
Can't withdraw money

### ISSUE THREAD

**Issue by lvng24** [solana-beach/issue-tracker#50]
https://github.com/user-attachments/assets/cadb9de5-1239-4dd8-b9c3-db91fa20d328

I have staking sol and recently I need to withdraw money but when I withdraw I have low gas fee error but I cannot choose which item to change gas fee (as attached video). I reflected the above issue with okx, but they responded that it might be because of the house's fault as well. So what's the fault here? I hope to receive early response and resolve the above issue as soon as possible. my sol address : 2Uh2HamdRkF6R5pzigJKtJnPuwq93FqAb7F6QtQcN4tN

**Comment by SimonKraus** [comment]
This is absolutely the wrong place to open an issue. 
Looks like an gas estimate error in the OKX app.
