### ISSUE TITLE
Validator details "uptime" statistic is badly named

### ISSUE THREAD

**Issue by bji** [solana-beach/issue-tracker#7]
**Describe the bug**
I'm calling this a bug.  Validator details "uptime" statistic is badly named.  It has nothing to do with "uptime" in the traditional sense and gives the impression that all of our validators are "down" at least 5% - 10% of the time.  It's just super confusing.  Please choose a better name than "uptime", like "Successful slots", or something.

**Comment by rpd089** [comment]
Very good point! We'll discuss a new name internally - what do you think about calling it 'Slot success rate?

**Comment by bji** [comment]
I think that "Slot success rate" would be perfect.
