### ISSUE TITLE
Change default sorting of validators

### ISSUE THREAD

**Issue by bji** [solana-beach/issue-tracker#9]
**Is your feature request related to a problem? Please describe.**
Please find some different way to default sort validators than by stake.  You are contributing to the centralization of Solana by "featuring" the largest validators first.

**Describe the solution you'd like**
Randomize them?  I don't know exactly, there are many possible solutions, I don't know how much effort you want to put into it.  But find some way to change it, it's crippling to Solana to have stake keep piling up on the largest validators.

**Comment by rpd089** [comment]
This is a tough nut - we definitely do not want to contribute to the centralization of the network and I think that our efforts have shown this already. We went with the current solution as it does make sense for stakeholders to directly see who the biggest players are / who can halt the network. 

Now that the 'halt power' bar continues to move down (which is great!), it is below the fold and therefore not as easy to spot anymore. We are brainstorming about how we can best nudge token holders to help with the decentralization of the network - a quick fix could be to implement an 'info box' above the list to state the importance of delegators helping with the decentralization of the network (like the great Ben Parker put it so nicely: 'With great power comes great responsibility'). We will iterate on this time and time again to come up with a solution that works best for everybody.

**Comment by bji** [comment]
To some degree that line is an illusion anyway though.  Because you don't need only those top stake sized validators to halt the network.  You need *any* set of validators whose sum stake total is at least 33% of the network.  Having the line is useful because it kind of shows the "smallest set of validators that need to be compromised to halt the network", but at the same time it may mislead people into believing that this is the *only* set that can half the network.

**Comment by rpd089** [comment]
Yeah good point, thanks for sharing that. We'll discuss this and tinker with a few solutions - super valuable input, bji!

**Comment by bji** [comment]
Hey nice work with the change to the solanabeach.io site that by default hides validators above the halt line.  That is an interesting solution to the problem!

It was also suggested in Discord that another enhancement might be to also hide the "100% commission" validators since they are not seeking stake.  Now that you have the code logic to hide validators in this way, maybe you can make a section at the bottom that similarly hides 100% commission validators.  Just an idea!

**Comment by rpd089** [comment]
Thanks, @bji :) That's an interesting idea, thanks for sharing! We'll tinker around a bit with different approaches to this - maybe users can toggle something to have them shown or not -- appreciate your community work in discord man, you're constantly hammering away!
